title: Andy Leuckert
description: Audio · Embedded · Creative Technology
theme: minima
url: "https://anleu.github.io"
baseurl: ""

# Author settings (wird im Footer und Feeds verwendet)
author: Andy Leuckert

# Minima settings
minima:
  skin: auto
  social_links:
    # Hier können Social Media Links hinzugefügt werden:
    # github: anleu
    # twitter: username
    # linkedin: username

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
