title: Andy Leuckert
description: Audio · Embedded · Creative Technology
theme: minima
url: "https://anleu.github.io"
baseurl: ""
logo: /assets/images/091Logo_black.png

# Header Navigation - Reihenfolge der Seiten im Menü
header_pages:
  - index.md
  - music.md
  - plugins.md
  - projects.md
  - contact.md

# Minima settings
minima:
  skin: auto
  social_links:
    # Hier können Social Media Links hinzugefügt werden:
    # github: anleu
    # twitter: username
    # linkedin: username

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
